paths:
  uploads: uploads
  static: ''
  dam_uploads: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  pages:
    path: ''
    output: true
    filter: strict
    description: ''
    icon: notes
    _editables:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default page:
        path:
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name:
        icon: notes
        preview:
        _editables:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:


_inputs:
  layout:
    type: text
    hidden: true
    cascade: true
  id:
    type: text
    hidden: true
    cascade: true
  text-html:
    type: html
    options:
      allow_resize: true
      allow_custom_markup: false
      remove_custom_markup: false
      initial_height: 320
      format: p h1 h2 h3 a img
      italic: true
      bold: true
      horizontalrule: true
      image: true
      image_size_attributes: true
      link: true
      resize_style: contain
      snippet: false
      styles: /editor.css
    label: Content
    cascade: true
  height:
    type: select
    options:
      allow_empty: true
      values:
        50vh: half screen 
        75vh: three quaters screen
        90vh: just short of full screen
        100vh: full screen
    cascade: true
  width:
    type: select
    options:
      allow_empty: true
      values:
        30%: one-third
        50%: half
        80%: just short of full width
        100%: full width
    cascade: true
  horizontal-placement:
    type: select
    options:
      allow_empty: false
      values:
        - left
        - center
        - right
    cascade: true
  vertical-placement:
    type: select
    options:
      allow_empty: false
      values:
        - top
        - center
        - bottom
    cascade: true
  text-alignment:
    type: select
    options:
      allow_empty: false
      values:
        - left
        - center
        - right
    cascade: true
  large-text-alignment:
    type: select
    options:
      allow_empty: false
      values:
        - left
        - center
        - right
    cascade: true
  paragraph-text-alignment:
    type: select
    options:
      allow_empty: false
      values:
        - left
        - center
        - right
    cascade: true
  opacity:
    type: select
    options:
      allow_empty: true
      values:
        - 10%
        - 20%
        - 30%
        - 40%
        - 50%
        - 60%
        - 70%
        - 80%
        - 90%
        - 100%
    cascade: true
  button-alignment:
    type: select
    options:
      allow_empty: false
      values:
        - right
        - center
        - left
    label: Button placement
    comment: Choose where the button is placed in relation to the form
    cascade: true
  large-text-width:
    type: select
    options:
      allow_empty: false
      values:
        - half
        - full
    label: Large text width
    comment: Choose whether the large text takes up half or the full width of the page
    cascade: true
  paragraph-width:
    type: select
    options:
      allow_empty: false
      values:
        - half
        - full
    label: Paragraph text width
    comment: >-
      Choose whether the paragraph text takes up half or the full width of the
      page
    cascade: true
  scheme-name:
    type: select
    options:
      allow_empty: true
      values:
        - base
        - dark
        - featured
        - brown
    label: Color scheme for the block
    comment: >-
      Choose which background color to use, then the text, button and highlight
      colors will be chosen automatically
    cascade: true

_structures:
  blocks:
    style: modal
    values:
      - label: text block
        value:
          id: rich-text 
          text-html: Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis deserunt, doloribus incidunt beatae id distinctio consectetur aut fugiat magnam, nam maiores exercitationem reiciendis molestiae tempora quaerat cumque itaque possimus dolore?
          height: 40vh
          width: 100%
          horizontal-placement: center
          vertical-placement: center
          text-alignment: center
          scheme-name: dark
      - label: photo-banner
        value:
          id: photo-banner 
          text-html: Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis deserunt, doloribus incidunt beatae id distinctio consectetur aut fugiat magnam, nam maiores exercitationem reiciendis molestiae tempora quaerat cumque itaque possimus dolore?
          height: 80vh
          width: 100%
          horizontal-placement: center
          vertical-placement: center
          text-alignment: center
          image: https://picsum.photos/id/1025/600/400
          alt:
          scheme-name:
          overlay:
            color: 
            opacity: 
      - label: text banner
        value:
          id: text-banner
          heading_html:
          text_html:
          large-text-width:
          paragraph-width:
          large-text-placement:
          large-text-alignment:
          paragraph-text-alignment:
          button-alignment:
          button-1-text:
          button-1-link:
          button-2-text:
          button-2-link:
          scheme-name:
      - label: accordion
        value:
          id: accordion
          section-heading: This is a heading
          heading-text-alignment: left
          faq-text-alignment: left
          faq-loop:
            - question: Lorem ipsum dolor sit amet consectetur adipisicing elit?
              answer-html: Harum tempora rerum debitis! Quo fugiat eius accusamus suscipit dignissimos aspernatur aliquid nisi repellat expedita veritatis saepe, delectus, dolorem consequatur autem fugit.
            - question: Lorem ipsum dolor sit amet consectetur adipisicing elit?
              answer-html: Harum tempora rerum debitis! Quo fugiat eius accusamus suscipit dignissimos aspernatur aliquid nisi repellat expedita veritatis saepe, delectus, dolorem consequatur autem fugit.
            - question: Lorem ipsum dolor sit amet consectetur adipisicing elit?
              answer-html: Harum tempora rerum debitis! Quo fugiat eius accusamus suscipit dignissimos aspernatur aliquid nisi repellat expedita veritatis saepe, delectus, dolorem consequatur autem fugit.
          scheme-name:
      - label: form
        value:
          id: form
          button-alignment: center
          submit-button-text: Submit
          inputs:
          - type: text
            name: First name
            label: First name
            placeholder-text: John
            width: half
            required: true
          - type: text
            name: Last name
            label: Last name
            placeholder-text: Smith
            width: half
            required: true
          - type: email
            name: Email
            label: Your Email
            placeholder-text: yourname@gmail.com
            width: full
            required: true
          - type: phone
            name: Phone
            label: Cell phone
            placeholder-text: 612-555-5555
            width: full
            required: false
          - form-type: checkbox
            label: >-
              I would be interested in volunteering for the following (check all
              that apply):
            width: full
            boxes:
              - checkbox-option: Packing Party
              - checkbox-option: Special Events
              - checkbox-option: Making Memories
              - checkbox-option: Internship
          - type: textarea
            name: Inquiry
            label: Your message here
            placeholder-text: Add placeholder text here...
            width: full
            required: true
          scheme-name:
      - label: ticker-banner
        value:
          id: ticker-banner
          banner-style:
            direction: English
            speed: 50
            text-size:
          banner-message:
          - text: Lorem ipsum dolor sit!
            url:
          - text: Doloribus incidunt beatae!
            url:
          - text: Dexercitationem reiciendis!
            url:
          scheme-name:
      - label: cards
        value:
          id: cards
          section-heading_html: heading
          card-description: true
          text-alignment: left
          card-loop:
          - heading: Service 1
            short-description_html: Aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur.
            button-text: Learn More
            button-link: /services#section-1
            image: /images/keys.jpg
            alt: 
          - heading: Service 2
            short-description_html: Similique sunt in culpa qui officia deserunt mollitia animi. Et harum quidem rerum facilis est et expedita.
            button-text: Learn More
            button-link: /services#section-2
            image: /images/keys.jpg
            alt: 
          - heading: Service 3
            short-description_html: am libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat.
            button-text: Learn More
            button-link: /services#section-3
            image: /images/keys.jpg
            alt: 
          scheme-name: base
  
  
  header_links:
    style: modal
    values:
      - label: simple link
        value:
          link: /
          text: home
      - label: link with sublinks
        value:
          text: home
          link: /
          sub_links:
            - text: sublink 1
              link: /
            - text: sublink 2
              link: /
            - text: sublink 3
              link: /
